### ISSUE TITLE
tests not working on fresh checkout

### ISSUE THREAD

**Issue by fbergmann** [fromzeroedu/flogger#1]
I've noticed that the tests are no longer working on windows in the current version. The tests start working after adding markdown support for the rendering. Then running: 

```
python tests.py
```

fails on import of the Markdown package with stack trace: 

```
======================================================================
ERROR: blog.tests (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: blog.tests
Traceback (most recent call last):
  File "c:\Anaconda2_32\envs\py37\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "c:\Anaconda2_32\envs\py37\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "E:\Development\flask_flogger\blog\tests.py", line 11, in <module>
    from author.models import Author
  File "E:\Development\flask_flogger\author\models.py", line 1, in <module>
    from application import db
  File "E:\Development\flask_flogger\application.py", line 4, in <module>
    from flaskext.markdown import Markdown
  File "E:\Development\flask_flogger\venv\lib\site-packages\flaskext\markdown.py", line 33, in <module>
    import markdown as md
  File "E:\Development\flask_flogger\venv\lib\site-packages\markdown\__init__.py", line 25, in <module>
    from .core import Markdown, markdown, markdownFromFile
  File "E:\Development\flask_flogger\venv\lib\site-packages\markdown\core.py", line 29, in <module>
    import pkg_resources
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 3192, in <module>
    @_call_aside
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 3176, in _call_aside
    f(*args, **kwargs)
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 3220, in _initialize_master_working_set
    for dist in working_set
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 3220, in <genexpr>
    for dist in working_set
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 2727, in activate
    declare_namespace(pkg)
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 2253, in declare_namespace
    _handle_ns(packageName, path_item)
  File "E:\Development\flask_flogger\venv\lib\site-packages\pkg_resources\__init__.py", line 2170, in _handle_ns
    loader = importer.find_module(packageName)
  File "<frozen importlib._bootstrap_external>", line 431, in _find_module_shim
  File "<frozen importlib._bootstrap_external>", line 1346, in find_loader
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
AttributeError: 'WindowsPath' object has no attribute 'rstrip'


```

this happens both with new python environments for python 3.6 and 3.7.

**Comment by fbergmann** [comment]
Just wanted to add, that running the app normally with `flask run` or `flask shell` works fine, even with the markdown package import statement there. So there must be something different going on when loaded with the unittest loader

**Comment by esfoobar** [comment]
Thanks, I'll take a look.

**Comment by michael-a-green** [comment]
I'm having the same issue. I'm using Anaconda python 2019.07

**Comment by bkline** [comment]
Still broken (python 3.6, 3.7, and 3.8). Any progress on your end, Jorge?
